version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - staticcheck

linters-settings:
  gosec:
    excludes:
      - G304

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
